FROM nvidia/cuda
RUN apt-get update \
 && apt-get install --no-install-recommends -y gcc build-essential
RUN mkdir -p /opt/darknet
RUN mkdir -p /opt/bin
COPY . /opt/darknet
WORKDIR /opt/darknet
RUN sed -i -e '1s/GPU=0/GPU=1/g' Makefile
RUN make -j8
RUN cp darknet /opt/bin
