FROM nvidia/cuda:10.1-cudnn7-devel
RUN http_proxy=http://172.16.153.103:3128 apt-get update \
 && http_proxy=http://172.16.153.103:3128 apt-get install --no-install-recommends -y gcc build-essential cmake wget software-properties-common
RUN mkdir -p /opt/darknet
RUN mkdir -p /opt/bin
COPY . /opt/darknet
WORKDIR /opt/darknet
RUN sed -i -e '1s/GPU=0/GPU=1/g' Makefile
RUN make -j8
RUN cp darknet /opt/bin
